#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-purestorage
Version  : 1.19.0
Release  : 2
URL      : https://github.com/purestorage/rest-client/archive/1.19.0.tar.gz
Source0  : https://github.com/purestorage/rest-client/archive/1.19.0.tar.gz
Summary  : Pure Storage FlashArray REST Client
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-purestorage-license = %{version}-%{release}
Requires: pypi-purestorage-python = %{version}-%{release}
Requires: pypi-purestorage-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(requests)

%description
# This file and parent directory solely exist to suppress documentation build warnings.

%package license
Summary: license components for the pypi-purestorage package.
Group: Default

%description license
license components for the pypi-purestorage package.


%package python
Summary: python components for the pypi-purestorage package.
Group: Default
Requires: pypi-purestorage-python3 = %{version}-%{release}

%description python
python components for the pypi-purestorage package.


%package python3
Summary: python3 components for the pypi-purestorage package.
Group: Default
Requires: python3-core
Provides: pypi(purestorage)
Requires: pypi(requests)

%description python3
python3 components for the pypi-purestorage package.


%prep
%setup -q -n rest-client-1.19.0
cd %{_builddir}/rest-client-1.19.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639061103
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-purestorage
cp %{_builddir}/rest-client-1.19.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-purestorage/2b874e6b1e7f063ef687afd4395bdd1263ac700f
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-purestorage/2b874e6b1e7f063ef687afd4395bdd1263ac700f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
